#!/usr/bin/env python3
"""Emit Swift string literals for inventory ids (parity gate + a11y presence)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "macos/GhidraVibe/Sources/GhidraVibe/StockParityIds.generated.swift"


def main() -> int:
    ids: list[str] = []
    for inv in sorted((ROOT / "native-ui/parity").glob("*.inventory.json")):
        data = json.loads(inv.read_text())
        for e in data.get("entries", []):
            if e.get("surface") in (
                "main_toolbar",
                "provider_toolbar",
                "project_toolbar",
                "tool_chest",
                "provider_body",
            ):
                ids.append(e["id"])
    ids = sorted(set(ids))
    lines = [
        "// Generated by scripts/generate-stock-parity-ids.py — do not edit.",
        "enum StockParityIds {",
        "    /// All stock inventory control ids referenced for parity gates.",
        "    static let all: [String] = [",
    ]
    for i in ids:
        lines.append(f'        "{i}",')
    lines += ["    ]", "}", ""]
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(ids)} ids)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
